#公共配置
server:
  #端口
  port: 8082
  tomcat:
    uri-encoding: UTF-8
spring:
  redis:
    host: 192.168.2.86
    port: 6379
    database: 0
    timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
       # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1        
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    
    
########################### queue 配置 ##########################
 
mq:
  env: test
register:
  exchange:
    name: ${mq.env}.user.register.exchange
  delay:
    queue:
      name: ${mq.env}.user.register.delay.queue
    exchange:
     name: ${mq.env}.user.register.delay.exchange
  queue:
    name: ${mq.env}.user.register.queue
 
 
