server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validationQuery: SELECT 1 FROM DUAL
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
      filters: stat,wall,logback
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 60s
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-wait: -1s
        max-active: -1
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
mq:
  env: test
register:
  exchange:
    name: ${mq.env}.user.register.exchange
  delay:
    queue:
      name: ${mq.env}.user.register.delay.queue
    exchange:
      name: ${mq.env}.user.register.delay.exchange
  queue:
    name: ${mq.env}.user.register.queue
trade:
  record:
    ttl: 10000
mybatis:
  type-aliases-package: com.ughen.saas.entity
  mapper-locations: classpath:mapper/*.xml
  mapUnderscoreToCamelCase: true
api:
  swagger:
    title: 优正SAAS平台
    description: 优正科技
    version: v1.0
    basePackage: com.ughen.saas.backstage
logging:
  config: classpath:logback-spring.xml
  path: D:/logs/saas
foo: foo version 4