#公共配置
server:
  #端口
  port: 8085
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    active: dev
  #连接池配置
  datasource:
    url: jdbc:mysql://192.168.2.17:3306/saas1?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
    username: root
    password: youzh5ng
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 配置测试查询语句
      validationQuery: SELECT 1 FROM DUAL
      # 初始化大小，最小，最大
      initialSize: 10
      minIdle: 10
      maxActive: 200
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,logback
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
 

  redis:
    host: 192.168.2.86
    port: 6379
    database: 0
    timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
       # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1

        
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    
    
########################### queue 配置 ##########################
 
mq:
  env: test
register:
  exchange:
    name: ${mq.env}.user.register.exchange
  delay:
    queue:
      name: ${mq.env}.user.register.delay.queue
    exchange:
     name: ${mq.env}.user.register.delay.exchange
  queue:
    name: ${mq.env}.user.register.queue
 
 
#交易记录失效时间：10s
trade: 
  record:
    ttl: 10000
    

#mybatis
mybatis:
  # 实体类扫描
  type-aliases-package: com.ughen.saas.entity
  # 配置映射文件位置
  mapper-locations: classpath:mapper/*.xml
  # 开启驼峰匹配
  mapUnderscoreToCamelCase: true
  
api:
  swagger:
    title: 优正SAAS平台
    description: 优正科技
    version: v1.0
    basePackage: com.ughen.saas.backstage

management:
  endpoints:
    web:
      exposure:
        include: "*"



logging:
  config: classpath:logback-spring.xml
  path: D:/logs/saas


